baseURL = "http://hritik-saini.github.io/"
title ="Hritik saini"
theme = "hugo-theme-cleanwhite-rsy"
languageCode = "en-us"
paginate = 5000 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  SEOTitle = "Hritk saini blog"
  keyword = "Ctf player , hacker , pentester , hackthebox , tryhackme, IIT Roorkee , blog , writeups , hacking  " 

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  email          = "hritiksaini2015@gmail.com"
  github         = "https://github.com/hritik-saini"
  instagram     =  "https://www.instagram.com/hritiksaini__/"

